#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  5 18:05:12 2017

@author: bhumihar
"""
import time
start_time = time.time()

def max_rupee(a) :
    
    #val1 = min(a) ;
    #val2 = max(a) ;
    min_inx = []  ;
    max_inx = [] ;
    
    val1 = a[0] ;
    val2 = a[0]
    
    for i in range(10) :
        if (val1 > a[i]) :
            min_inx = []  ;
            val1 = a[i]
            min_inx.append(i) 
        elif (val1==a[i]) :
            min_inx.append(i) 
        if (val2 < a[i]):
            max_inx = []
            val2 = a[i]
            max_inx.append(i)
        elif (val2 == a[i]) :
            max_inx.append(i)
        
            
            
    #print(min_inx)
    #print(max_inx)
    
    if (max_inx[0]<min_inx[-1]) :
        #print('okkkk')
        a[min_inx[-1]] = val2 ;
        a[max_inx[0]] = val1 ;
        
        
    #print(a)
    val4 = sum([(i+1)*a[i] for i in range(10)])
    return val4


a1 = [1, 2, 3, 2, 1, 5, 3, 1, 5, 5] ;
a = [-1, 2, 3, -2, 1, 5, 3, 1, -5, 5] ;

print(max_rupee(a1))

print("--- %s seconds ---" % (time.time() - start_time))